sudo: false
language: python
python:
  - 3.5
services:
  - postgresql
before_install:
  - psql -c 'create database testdb;' -U postgres
  - export DJANGO_SETTINGS_MODULE=config.settings.travis
  - export DATABASE_URL=postgres://postgres@localhost/testdb
install:
  - pip install -r requirements/travis.txt
script:
  - python manage.py migrate
  - flake8 --exclude=migrations,settings,manage.py
  - python manage.py test
